version: '3.7'

services:
  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - /app/node_modules
    command: npm run start:dev
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /app/src
          ignore:
            - node_modules/
        - action: sync
          path: ./backend/package.json
          target: /app/package.json
        - action: rebuild
          path: ./backend/package-lock.json

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
        - '5173:5173'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - REACT_APP_API_URL=http://localhost:3000
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run dev
    depends_on:
      - backend
    env_file:
      - ./frontend/.env

volumes:
    postgres_data:
